name = "place-worker"
main = "src/index.js"
workers_dev = true
compatibility_date = "2024-06-20"

[[routes]]
pattern = "neurosama.place"
zone_name = "neurosama.place"
custom_domain = true

[[migrations]]
tag = "v1"
new_classes = [ "GridDurableObject" ]

[observability]
enabled = false

  [observability.logs]
  enabled = true
  invocation_logs = false

[vars]
DISCORD_CLIENT_ID = "1388712213002457118"

[[durable_objects.bindings]]
name = "GRID_STATE"
class_name = "GridDurableObject"

[[kv_namespaces]]
id = "b3eec4eb85824139ab2a7dbef0b30a08"
binding = "__STATIC_CONTENT"
