# wrangler.toml - The final, correct version

name = "place-worker"
main = "src/index.js"
compatibility_date = "2024-06-20"

# Static assets configuration
assets = { directory = "./public" }

[[durable_objects.bindings]]
name = "GRID_STATE"
class_name = "GridDurableObject"

[[migrations]]
tag = "v1"
new_classes = ["GridDurableObject"]

[vars]
DISCORD_CLIENT_ID = "1388712213002457118"

[observability.logs]
enabled = true
